export const cardInfo = [
  {
    id: 1,
    title: "Ronin#597",
    subtitle: "77-bit",
    value: 0.32,
    img: process.env.PUBLIC_URL + "/images/Ronin597createt77bit.jpg",
    like: 21,
    creatorName: "77-bit",
    collectionType: "Recommended",
  },
  {
    id: 2,
    title: "Ronin#154",
    subtitle: "77-bit",
    value: 0.5,
    img: process.env.PUBLIC_URL + "/images/ronin154created77bitvalue0.5.jpg",
    like: 27,
    creatorName: "77-bit",
    collectionType: "Recommended",
  },
  {
    id: 3,
    title: "Ronin#742",
    subtitle: "77-bit",
    value: 0.37,
    img: process.env.PUBLIC_URL + "/images/ronin742created77bitvalue0.37.jpg",
    like: 34,
    category: true,
    creatorName: "77-bit",
    collectionType: "Recommended",
  },
  {
    id: 4,
    title: "Ronin#1386",
    subtitle: "77-bit",
    value: 0.34,
    img: process.env.PUBLIC_URL + "/images/ronin1386created77bitvalue0.34.jpg",
    like: 25,
    category: true,
    creatorName: "77-bit",
    collectionType: "Recommended",
  },
  {
    id: 5,
    title: "Ronin#1591",
    subtitle: "77-bit",
    value: 0.34,
    img: process.env.PUBLIC_URL + "/images/ronin1591created77bitvalue0.34.jpg",
    like: 35,
    category: true,
    creatorName: "77-bit",
    collectionType: "Recommended",
  },
  {
    id: 6,
    title: "Ronin#2689",
    subtitle: "77-bit",
    value: 7.7,
    img: process.env.PUBLIC_URL + "/images/ronin2689created77bitvalue7.7.jpg",
    like: 356,
    category: true,
    creatorName: "77-bit",
    collectionType: "Popular",
  },
  {
    id: 7,
    title: "Ronin#3001",
    subtitle: "77-bit",
    value: 420,
    img: process.env.PUBLIC_URL + "/images/ronin3001created77bitvalue402.jpg",
    like: 490,
    category: true,
    creatorName: "77-bit",
    collectionType: "Popular",
  },
  {
    id: 8,
    title: "Ronin#4787",
    subtitle: "77-bit",
    value: 0.37,
    img: process.env.PUBLIC_URL + "/images/ronin4787created77bitvalue0.37.jpg",
    like: 10,
    category: true,
    creatorName: "77-bit",
    collectionType: "Recommended",
  },
  {
    id: 9,
    title: "Ronin#6209",
    subtitle: "77-bit",
    value: 0.32,
    img: process.env.PUBLIC_URL + "/images/ronin6209created77bitvalue0.32.jpg",
    like: 15,
    category: true,
    creatorName: "77-bit",
    collectionType: "Recommended",
  },
  {
    id: 10,
    title: "Ronin#6927",
    subtitle: "77-bit",
    value: 0.33,
    img: process.env.PUBLIC_URL + "/images/ronin6927created77bitvalue0.33.jpg",
    like: 40,
    category: true,
    creatorName: "77-bit",
    collectionType: "Popular",
  },
  {
    id: 11,
    title: "Azuki#5936",
    subtitle: "Azuki",
    value: 7,
    img: process.env.PUBLIC_URL + "/images/azuki5936createdazukivalue7.jpg",
    like: 490,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Recommended",
  },
  {
    id: 12,
    title: "Azuki#5852",
    subtitle: "Azuki",
    value: 15,
    img: process.env.PUBLIC_URL + "/images/azuki5852createdbyazukivalue15.jpg",
    like: 459,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Popular",
  },
  {
    id: 13,
    title: "Azuki#5672",
    subtitle: "Azuki",
    value: 8,
    img: process.env.PUBLIC_URL + "/images/azuki5672createdbyAzukivalue8.jpg",
    like: 169,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Recommended",
  },
  {
    id: 14,
    title: "Azuki#5442",
    subtitle: "Azuki",
    value: 9.2,
    img: process.env.PUBLIC_URL + "/images/azuki5442createdbyAzukivalue9.2.jpg",
    like: 168,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Popular",
  },
  {
    id: 15,
    title: "Azuki#3790",
    subtitle: "Azuki",
    value: 7.2,
    img: process.env.PUBLIC_URL + "/images/azuki3790createdbyazukivalue7.2.jpg",
    like: 124,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Recommended",
  },
  {
    id: 16,
    title: "Azuki#3344",
    subtitle: "Azuki",
    value: 7,
    img: process.env.PUBLIC_URL + "/images/azuki3344createdbyAzukivalue7.jpg",
    like: 233,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Recommended",
  },
  {
    id: 17,
    title: "Clonex_2846",
    subtitle: "Clonex-X",
    value: 25,
    img: process.env.PUBLIC_URL + "/images/clonex2846createdclonexvalue25.jpg",
    like: 198,
    creatorName: "Clonex-X",
    collectionType: "Popular",
  },
  {
    id: 18,
    title: "Clonex_13443",
    subtitle: "Clonex-X",
    value: 55,
    img:
      process.env.PUBLIC_URL + "/images/clonex13443createdbyclonexvalue55.jpg",
    like: 321,
    creatorName: "Clonex-X",
    collectionType: "Popular",
  },
  {
    id: 19,
    title: "Clonex_16246",
    subtitle: "Clonex-X",
    value: 35,
    img: process.env.PUBLIC_URL + "/images/clonex16246createdclonexvalue56.jpg",
    like: 243,
    creatorName: "Clonex-X",
    collectionType: "Popular",
  },
  {
    id: 20,
    title: "#2280",
    subtitle: "Bored Ape",
    value: 335,
    img: process.env.PUBLIC_URL + "/images/2280createdbyBoredApevalue335.jpg",
    like: 890,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Popular",
  },
  {
    id: 21,
    title: "#2535",
    subtitle: "Bored Ape",
    value: 335,
    img: process.env.PUBLIC_URL + "/images/2535createdByBoredApevalue335.jpg",
    like: 245,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Popular",
  },
  {
    id: 22,
    title: "#2643",
    subtitle: "Bored Ape",
    value: 190,
    img: process.env.PUBLIC_URL + "/images/2643createdByBoredApevalue190.jpg",
    like: 154,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Recommended",
  },
  {
    id: 23,
    title: "#4067",
    subtitle: "Bored Ape",
    value: 49,
    img: process.env.PUBLIC_URL + "/images/4067createdByBoredApevalue49.jpg",
    like: 556,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Recommended",
  },
  {
    id: 24,
    title: "#5374",
    subtitle: "Bored Ape",
    value: 115,
    img: process.env.PUBLIC_URL + "/images/5374createdByBoredApevalue115.jpg",
    like: 500,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Popular",
  },
  {
    id: 25,
    title: "#6014",
    subtitle: "Bored Ape",
    value: 360,
    img: process.env.PUBLIC_URL + "/images/6014createdByBoredApevalue360.jpg",
    like: 1025,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Popular",
  },
  {
    id: 26,
    title: "#6655",
    subtitle: "Bored Ape",
    value: 55,
    img: process.env.PUBLIC_URL + "/images/6655createdByBoredApevalue55.jpg",
    like: 432,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Recommended",
  },
  {
    id: 27,
    title: "#7801",
    subtitle: "Bored Ape",
    value: 190,
    img: process.env.PUBLIC_URL + "/images/7801createdbyboredApevalue190.jpg",
    like: 432,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Popular",
  },
  {
    id: 28,
    title: "#7923",
    subtitle: "Bored Ape",
    value: 45,
    img: process.env.PUBLIC_URL + "/images/7923createdByBoredApevalue45.jpg",
    like: 230,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Recommended",
  },
  {
    id: 29,
    title: "#9224",
    subtitle: "Bored Ape",
    value: 120,
    img: process.env.PUBLIC_URL + "/images/9224createdByBoredApevalue120.jpg",
    like: 180,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Recommended",
  },
  {
    id: 30,
    title: "#9542",
    subtitle: "Bored Ape",
    value: 95,
    img: process.env.PUBLIC_URL + "/images/9542createdByBoredApevalue95.jpg",
    like: 229,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Recommended",
  },
  {
    id: 31,
    title: "24",
    subtitle: "The Mona Lana",
    value: 0.5,
    img: process.env.PUBLIC_URL + "/images/24createdthemonalanavalue0.5.jpg",
    like: 50,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 32,
    title: "42",
    subtitle: "The Mona Lana",
    value: 0.2,
    img: process.env.PUBLIC_URL + "/images/42createdthemonalanvalue0.2.jpg",
    like: 15,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 33,
    title: "57",
    subtitle: "The Mona Lana",
    value: 0.5,
    img: process.env.PUBLIC_URL + "/images/57createdthemonalanavalue0.5.jpg",
    like: 22,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 34,
    title: "68",
    subtitle: "The Mona Lana",
    value: 0.5,
    img: process.env.PUBLIC_URL + "/images/68createdthemonalanvalue0.5.jpg",
    like: 23,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 35,
    title: "87",
    subtitle: "The Mona Lana",
    value: 2,
    img: process.env.PUBLIC_URL + "/images/87createdthemonalanavalue2.jpg",
    like: 59,
    creatorName: "The Mona Lana",
    collectionType: "Popular",
  },
  {
    id: 36,
    title: "103",
    subtitle: "The Mona Lana",
    value: 0.3,
    img: process.env.PUBLIC_URL + "/images/103createdthemonalanavalue0.5.jpg",
    like: 11,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 37,
    title: "162",
    subtitle: "The Mona Lana",
    value: 0.4,
    img: process.env.PUBLIC_URL + "/images/162createdthemonalanavalue0.4.jpg",
    like: 15,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 38,
    title: "262",
    subtitle: "The Mona Lana",
    value: 0.5,
    img: process.env.PUBLIC_URL + "/images/262createdthemonalanvalue0.5.jpg",
    like: 9,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 39,
    title: "355",
    subtitle: "The Mona Lana",
    value: 0.3,
    img: process.env.PUBLIC_URL + "/images/355createdthemonalanavalue0.3.jpg",
    like: 12,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 40,
    title: "390",
    subtitle: "The Mona Lana",
    value: 0.4,
    img: process.env.PUBLIC_URL + "/images/390createdthemonalanavalue0.4.jpg",
    like: 23,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 41,
    title: "488",
    subtitle: "The Mona Lana",
    value: 0.5,
    img: process.env.PUBLIC_URL + "/images/488createdthemonalanavalue0.5.jpg",
    like: 28,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 42,
    title: "Azuki#5442",
    subtitle: "Azuki",
    value: 9.2,
    img: process.env.PUBLIC_URL + "/images/azuki5442createdbyAzukivalue9.2.jpg",
    like: 168,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Popular",
  },
  {
    id: 43,
    title: "262",
    subtitle: "The Mona Lana",
    value: 0.5,
    img: process.env.PUBLIC_URL + "/images/262createdthemonalanvalue0.5.jpg",
    like: 9,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 44,
    title: "#7801",
    subtitle: "Bored Ape",
    value: 190,
    img: process.env.PUBLIC_URL + "/images/7801createdbyboredApevalue190.jpg",
    like: 432,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Popular",
  },
  {
    id: 45,
    title: "Azuki#5672",
    subtitle: "Azuki",
    value: 8,
    img: process.env.PUBLIC_URL + "/images/azuki5672createdbyAzukivalue8.jpg",
    like: 169,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Recommended",
  },
  {
    id: 46,
    title: "390",
    subtitle: "The Mona Lana",
    value: 0.4,
    img: process.env.PUBLIC_URL + "/images/390createdthemonalanavalue0.4.jpg",
    like: 23,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 47,
    title: "Azuki#5672",
    subtitle: "Azuki",
    value: 8,
    img: process.env.PUBLIC_URL + "/images/azuki5672createdbyAzukivalue8.jpg",
    like: 169,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Recommended",
  },
  {
    id: 48,
    title: "#6655",
    subtitle: "Bored Ape",
    value: 55,
    img: process.env.PUBLIC_URL + "/images/6655createdByBoredApevalue55.jpg",
    like: 432,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Recommended",
  },
  {
    id: 49,
    title: "#7923",
    subtitle: "Bored Ape",
    value: 45,
    img: process.env.PUBLIC_URL + "/images/7923createdByBoredApevalue45.jpg",
    like: 230,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Recommended",
  },
  {
    id: 50,
    title: "Ronin#6927",
    subtitle: "77-bit",
    value: 0.33,
    img: process.env.PUBLIC_URL + "/images/ronin6927created77bitvalue0.33.jpg",
    like: 40,
    category: true,
    creatorName: "77-bit",
    collectionType: "Popular",
  },
  {
    id: 51,
    title: "Ronin#154",
    subtitle: "77-bit",
    value: 0.5,
    img: process.env.PUBLIC_URL + "/images/ronin154created77bitvalue0.5.jpg",
    like: 27,
    creatorName: "77-bit",
    collectionType: "Recommended",
  },
  {
    id: 52,
    title: "103",
    subtitle: "The Mona Lana",
    value: 0.3,
    img: process.env.PUBLIC_URL + "/images/103createdthemonalanavalue0.5.jpg",
    like: 11,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 53,
    title: "Ronin#3001",
    subtitle: "77-bit",
    value: 420,
    img: process.env.PUBLIC_URL + "/images/ronin3001created77bitvalue402.jpg",
    like: 490,
    category: true,
    creatorName: "77-bit",
    collectionType: "Popular",
  },
  {
    id: 54,
    title: "Ronin#6209",
    subtitle: "77-bit",
    value: 0.32,
    img: process.env.PUBLIC_URL + "/images/ronin6209created77bitvalue0.32.jpg",
    like: 15,
    category: true,
    creatorName: "77-bit",
    collectionType: "Recommended",
  },
  {
    id: 55,
    title: "Ronin#597",
    subtitle: "77-bit",
    value: 0.32,
    img: process.env.PUBLIC_URL + "/images/Ronin597createt77bit.jpg",
    like: 21,
    creatorName: "77-bit",
    collectionType: "Recommended",
  },
  {
    id: 56,
    title: "24",
    subtitle: "The Mona Lana",
    value: 0.5,
    img: process.env.PUBLIC_URL + "/images/24createdthemonalanavalue0.5.jpg",
    like: 50,
    creatorName: "The Mona Lana",
    collectionType: "Recommended",
  },
  {
    id: 57,
    title: "#9224",
    subtitle: "Bored Ape",
    value: 120,
    img: process.env.PUBLIC_URL + "/images/9224createdByBoredApevalue120.jpg",
    like: 180,
    category: true,
    creatorName: "Bored Ape",
    collectionType: "Recommended",
  },
  {
    id: 58,
    title: "Azuki#5936",
    subtitle: "Azuki",
    value: 7,
    img: process.env.PUBLIC_URL + "/images/azuki5936createdazukivalue7.jpg",
    like: 490,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Recommended",
  },
  {
    id: 59,
    title: "Azuki#3790",
    subtitle: "Azuki",
    value: 7.2,
    img: process.env.PUBLIC_URL + "/images/azuki3790createdbyazukivalue7.2.jpg",
    like: 124,
    inCollection: true,
    category: true,
    creatorName: "Azuki",
    collectionType: "Recommended",
  },
  {
    id: 60,
    title: "Clonex_16246",
    subtitle: "Clonex-X",
    value: 35,
    img: process.env.PUBLIC_URL + "/images/clonex16246createdclonexvalue56.jpg",
    like: 243,
    creatorName: "Clonex-X",
    collectionType: "Popular",
  },
];
