version: "3.9"
services:
  postgres:
    container_name: testDBAlex
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
    expose:
      - 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  

volumes:
  postgres_data: