export const userData = [
  {
    id: 1,
    img: process.env.PUBLIC_URL + "/images/product1.png",
    volume: "8,456",
    floorprice: "3.5",
    userName: "Alex Ca.",
    userNick: "by Alex",
    profit: "+27.5%",
    owners: "2.2k",
    items: 500,
  },
  {
    id: 2,
    img: process.env.PUBLIC_URL + "/images/avatar2.jpeg",
    volume: "4,768",
    floorprice: "2.5",
    userName: "Tigran Sh.",
    userNick: "by Tigr",
    profit: "+13.5%",
    owners: "1.2k",
    items: 800,
  },
  {
    id: 3,
    img: process.env.PUBLIC_URL + "/images/product2.png",
    volume: "9,768",
    floorprice: "7.5",
    userName: "Jhon Tk.",
    userNick: "by Jhon",
    profit: "+35.5%",
    owners: "0.5k",
    items: 300,
  },
  {
    id: 4,
    img: process.env.PUBLIC_URL + "/images/product3.png",
    volume: "10,001",
    floorprice: "9.5",
    userName: "Richard Ml.",
    userNick: "by Rich",
    profit: "+55.5%",
    owners: "0.2k",
    items: 200,
  },
  {
    id: 5,
    img: process.env.PUBLIC_URL + "/images/profile1.png",
    volume: "8,456",
    floorprice: "3.5",
    userName: "Alex Ca.",
    userNick: "by Alex",
    profit: "+27.5%",
    owners: "2.2k",
    items: 500,
  },
  {
    id: 6,
    img: process.env.PUBLIC_URL + "/images/product5.png",
    volume: "4,768",
    floorprice: "2.5",
    userName: "Tigran Sh.",
    userNick: "by Tigr",
    profit: "+13.5%",
    owners: "1.2k",
    items: 800,
  },
  {
    id: 7,
    img: process.env.PUBLIC_URL + "/images/avatar1.jpeg",
    volume: "9,768",
    floorprice: "7.5",
    userName: "Jhon Tk.",
    userNick: "by Jhon",
    profit: "+35.5%",
    owners: "0.5k",
    items: 300,
  },
  {
    id: 8,
    img: process.env.PUBLIC_URL + "/images/profile1.png",
    volume: "10,001",
    floorprice: "9.5",
    userName: "Richard Ml.",
    userNick: "by Rich",
    profit: "+55.5%",
    owners: "0.2k",
    items: 200,
  },
  {
    id: 9,
    img: process.env.PUBLIC_URL + "/images/avatar1.jpeg",
    volume: "8,456",
    floorprice: "3.5",
    userName: "Alex Ca.",
    userNick: "by Alex",
    profit: "+27.5%",
    owners: "2.2k",
    items: 500,
  },
  {
    id: 10,
    img: process.env.PUBLIC_URL + "/images/product6.png",
    volume: "4,768",
    floorprice: "2.5",
    userName: "Tigran Sh.",
    userNick: "by Tigr",
    profit: "+13.5%",
    owners: "1.2k",
    items: 800,
  },
  {
    id: 11,
    img: process.env.PUBLIC_URL + "/images/avatar1.jpeg",
    volume: "9,768",
    floorprice: "7.5",
    userName: "Jhon Tk.",
    userNick: "by Jhon",
    profit: "+35.5%",
    owners: "0.5k",
    items: 300,
  },
  {
    id: 12,
    img: process.env.PUBLIC_URL + "/images/product5.png",
    volume: "10,001",
    floorprice: "9.5",
    userName: "Richard Ml.",
    userNick: "by Rich",
    profit: "+55.5%",
    owners: "0.2k",
    items: 200,
  },
  {
    id: 13,
    img: process.env.PUBLIC_URL + "/images/product1.png",
    volume: "8,456",
    floorprice: "3.5",
    userName: "Alex Ca.",
    userNick: "by Alex",
    profit: "+27.5%",
    owners: "2.2k",
    items: 500,
  },
  {
    id: 14,
    img: process.env.PUBLIC_URL + "/images/product2.png",
    volume: "4,768",
    floorprice: "2.5",
    userName: "Tigran Sh.",
    userNick: "by Tigr",
    profit: "+13.5%",
    owners: "1.2k",
    items: 800,
  },
  {
    id: 15,
    img: process.env.PUBLIC_URL + "/images/product3.png",
    volume: "9,768",
    floorprice: "7.5",
    userName: "Jhon Tk.",
    userNick: "by Jhon",
    profit: "+35.5%",
    owners: "0.5k",
    items: 300,
  },
  {
    id: 16,
    img: process.env.PUBLIC_URL + "/images/product4.png",
    volume: "10,001",
    floorprice: "9.5",
    userName: "Richard Ml.",
    userNick: "by Rich",
    profit: "+55.5%",
    owners: "0.2k",
    items: 200,
  },
];
