
export const ActionTypes = {
  SET_COINS: "SET_COINS",
  SET_LOADING: "SET_LOADING",
  SHOW_DROP_DOWN_MENU: "SHOW_DROP_DOWN_MENU",
  SHOW_DROP_DOWN_SORT: "SHOW_DROP_DOWN_SORT",
  SHOW_DROP_MENU_POS: "SHOW_DROP_MENU_POS",
  SHOW_DROP_MENU_POS_SORT: "SHOW_DROP_MENU_POS_SORT",
  SET_SORT_FILTER: "SET_SORT_FILTER",
  SET_ORDER_FILTER: "SET_ORDER_FILTER",
  SET_FILTER_SORT_TYPE: "SET_FILTER_SORT_TYPE",
};
