export const ActionsForAutor = {
  CHECK_EMAIL_VALIDATION:"CHECK_EMAIL_VALIDATION",
  CHECK_USER_NAME:"CHECK_USER_NAME",
  CHECK_IF_USER_AUTORIZED:"CHECK_IF_USER_AUTORIZED",
  CHECK_IF_USER_ALREADY_REGISTERED:"CHECK_IF_USER_ALREADY_REGISTERED",
  SEND_CODE_AFTER_EMAIL_CHECK:"SEND_CODE_AFTER_EMAIL_CHECK",
  GET_CODE_FROM_EMAIL:"GET_CODE_FROM_EMAIL",
  CHECK_IF_CODE_FIELD:"CHECK_IF_CODE_FIELD",
  SET_CODE_FROM_USER:"SET_CODE_FROM_USER",
  SHOW_MESSAGE_IF_INVALID_CODE:"SHOW_MESSAGE_IF_INVALID_CODE",
}